module WelcomeHelper

  def boho_seeds
    {
      'BLUSAS': [
        'CROP-3',
        'NORMAL-3',
        'LARGO-3',
        'MANGA LARGA - CLASICA-2',
        'MANGA LARGA - FLARE-2',
        'MANGA CORTA - MURCIELAGO-2',
        'MANGA CORTA - FLARE-2',
        'MANGA CORTA - CLASICA-2',
        'SIN MANGA-2',
        'TIRITAS-2',
        'COLD SHOULDER-2',
        'MANGA 3/4-2',
        'SUELTO-4',
        'NORMAL-4',
        'OVERSIZE-4',
        'CUELLO V-1',
        'CUELLO REDONDO-1',
        'ESCOTE CRUZADO (WRAP)-1',
        'PLUNGE (ESCOTADO)-1',
        'CUELLO BOTE-1',
        'PLUMETI-5',
        'JACQUARD-5',
        'BLUE JEAN-5',
        'TENCEL-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'LINO-5',
        'GAMUZA-5',
        'ALGODON-5',
        'FRANELA-5',
        'CREPE-5',
        'ENCAJE-5',
        'CUERO-5',
        'ECO CUERO-5',
        'COTELE-5',
        'LYCRA-5',
        'POPELINA-5',
        'CHIFFON-5',
        'BRODERIE-5',
        'CROCHET-5',
        'RIBBED-5',
        'WAFFLE-5',
        'LANA-5',
        'HILO-5',
        'OTRA-5',
        'FLORES-6',
        'TIE DYE-6',
        'PAISLEY-6',
        'LISO-6',
        'ENCAJE-12',
        'FLECOS-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'TRANSPARENCIA-12',
        'CORDON/TIRA-12',
        'ACANALADO-12',
        'NIDO ABEJA-12',
        'OJETILLOS-12',
      ],
      'POLERAS': [
        'CROP-3',
        'NORMAL-3',
        'LARGO-3',
        'MANGA LARGA - CLASICA-2',
        'MANGA LARGA - FLARE-2',
        'MANGA CORTA - MURCIELAGO-2',
        'MANGA CORTA - FLARE-2',
        'MANGA CORTA - CLASICA-2',
        'SIN MANGA-2',
        'TIRITAS-2',
        'COLD SHOULDER-2',
        'MANGA 3/4-2',
        'SUELTO-4',
        'NORMAL-4',
        'OVERSIZE-4',
        'CUELLO V-1',
        'CUELLO REDONDO-1',
        'ESCOTE CRUZADO (WRAP)-1',
        'PLUNGE (ESCOTADO)-1',
        'CUELLO BOTE-1',
        'TERCIOPELO-5',
        'PLUSH-5',
        'GAMUZA-5',
        'ALGODON-5',
        'CREPE-5',
        'ENCAJE-5',
        'LYCRA-5',
        'POPELINA-5',
        'CHIFFON-5',
        'BRODERIE-5',
        'CROCHET-5',
        'RIBBED-5',
        'WAFFLE-5',
        'LANA-5',
        'HILO-5',
        'OTRA-5',
        'CHEVRON (ZIGZAG)-6',
        'FLORES-6',
        'TIE DYE-6',
        'PAISLEY-6',
        'LISO-6',
        'ENCAJE-12',
        'FLECOS-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'TRANSPARENCIA-12',
        'CORDON/TIRA-12',
        'ACANALADO-12',
        'NIDO ABEJA-12',
        'OJETILLOS-12',
      ],
      'BODYS': [
        'MANGA LARGA - CLASICA-2',
        'MANGA LARGA - FLARE-2',
        'MANGA CORTA - MURCIELAGO-2',
        'MANGA CORTA - FLARE-2',
        'MANGA CORTA - CLASICA-2',
        'SIN MANGA-2',
        'TIRITAS-2',
        'COLD SHOULDER-2',
        'CUELLO V-1',
        'CUELLO REDONDO-1',
        'ESCOTE CRUZADO (WRAP)-1',
        'PLUNGE (ESCOTADO)-1',
        'CUELLO BOTE-1',
        'TERCIOPELO-5',
        'PLUSH-5',
        'ALGODON-5',
        'CREPE-5',
        'ENCAJE-5',
        'LYCRA-5',
        'POPELINA-5',
        'CHIFFON-5',
        'BRODERIE-5',
        'RIBBED-5',
        'HILO-5',
        'OTRA-5',
        'FLORES-6',
        'TIE DYE-6',
        'PAISLEY-6',
        'LISO-6',
        'ENCAJE-12',
        'FLECOS-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'TRANSPARENCIA-12',
        'OJETILLOS-12',
      ],
      'KIMONOS': [
        'MANGA LARGA - CLASICA-2',
        'MANGA CORTA - CLASICA-2',
        'JACQUARD-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'ALGODON-5',
        'CREPE-5',
        'ENCAJE-5',
        'LYCRA-5',
        'POPELINA-5',
        'CHIFFON-5',
        'BRODERIE-5',
        'OTRA-5',
        'CHEVRON (ZIGZAG)-6',
        'FLORES-6',
        'TIE DYE-6',
        'PAISLEY-6',
        'LISO-6',
        'ENCAJE-12',
        'FLECOS-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
      ],
      'ABRIGOS': [
        'CROP-3',
        'MEDIO-3',
        'TOBILLO-3',
        'LARGO-3',
        'SIN MANGA-2',
        'MANGA LARGA - CLASICA-2',
        'MANGA CORTA - CLASICA-2',
        'APRETADO-4',
        'SUELTO-4',
        'NORMAL-4',
        'OVERSIZE-4',
        'BLUE JEAN-5',
        'TENCEL-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'LINO-5',
        'GAMUZA-5',
        'ALGODON-5',
        'GABARDINA-5',
        'CUERO-5',
        'ECO CUERO-5',
        'PIEL-5',
        'PIEL SINTETICA-5',
        'LANA-5',
        'CHEVRON (ZIGZAG)-6',
        'FLORES-6',
        'LISO-6',
        'ENCAJE-12',
        'FLECOS-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'OJETILLOS-12',
        'OTRO-12',
        'NINGUNO-12',
        'CINTURON-12',
      ],
      'CHAQUETAS': [
        'CROP-3',
        'MEDIO-3',
        'TOBILLO-3',
        'LARGO-3',
        'SIN MANGA-2',
        'MANGA CORTA - CLASICA-2',
        'MANGA LARGA - CLASICA-2',
        'NORMAL-4',
        'OVERSIZE-4',
        'BLUE JEAN-5',
        'TENCEL-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'LINO-5',
        'GAMUZA-5',
        'ALGODON-5',
        'GABARDINA-5',
        'FRANELA-5',
        'CUERO-5',
        'ECO CUERO-5',
        'COTELE-5',
        'LANA-5',
        'OTRA-5',
        'PARKA-5',
        'FLORES-6',
        'TIE DYE-6',
        'PAISLEY-6',
        'LISO-6',
        'ENCAJE-12',
        'FLECOS-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'OJETILLOS-12',
        'OTRO-12',
        'NINGUNO-12',
        'CINTURON-12',
      ],
      'PARKAS': [
        'MEDIO-3',
        'TOBILLO-3',
        'LARGO-3',
        'PARKA-5',
        'FLORES-6',
        'TIE DYE-6',
        'PAISLEY-6',
        'LISO-6',
      ],
      'PONCHOS': [
        'LANA-5',
        'HILO-5',
        'CHEVRON (ZIGZAG)-6',
        'LISO-6',
      ],
      'VESTIDO': [
        'MINI-15',
        'MIDI-15',
        'MAXI-15',
        'DESIGUAL-15',
        'MANGA LARGA - CLASICA-2',
        'UNA MANGA-2',
        'MANGA CORTA - CLASICA-2',
        'SIN MANGA-2',
        'TIRITAS-2',
        'OFF SHOULDER-2',
        'COLD SHOULDER-2',
        'MANGA 3/4-2',
        'POLERA-16',
        'SLIP-16',
        'SMOCK-16',
        'WRAP-16',
        'CINTURA CAIDA (AÑOS 20)-16',
        'CORTE IMPERIO (ABAJO PECHUGA)-16',
        'SHIFT-16',
        'CUELLO V-1',
        'CUELLO REDONDO-1',
        'ESCOTE CRUZADO (WRAP)-1',
        'PLUNGE (ESCOTADO)-1',
        'PLUMETI-5',
        'JACQUARD-5',
        'BLUE JEAN-5',
        'TENCEL-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'LINO-5',
        'GAMUZA-5',
        'ALGODON-5',
        'CREPE-5',
        'ENCAJE-5',
        'LYCRA-5',
        'CHIFFON-5',
        'BRODERIE-5',
        'LANA-5',
        'HILO-5',
        'OTRA-5',
        'CHEVRON (ZIGZAG)-6',
        'FLORES-6',
        'TIE DYE-6',
        'PAISLEY-6',
        'LISO-6',
        'ENCAJE-12',
        'FLECOS-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'OJETILLOS-12',
        'CORDON/TIRA-12',
        'NINGUNO-12',
        'CINTURON-12',
        'ACANALADO-12',
        'NIDO ABEJA-12',
        'OTRO-12',
      ],
      'ENTERITOS': [
        'MINI-15',
        'MIDI-15',
        'MAXI-15',
        'MANGA LARGA - CLASICA-2',
        'MANGA LARGA - FLARE-2',
        'MANGA CORTA - MURCIELAGO-2',
        'MANGA CORTA - FLARE-2',
        'MANGA CORTA - CLASICA-2',
        'SIN MANGA-2',
        'TIRITAS-2',
        'COLD SHOULDER-2',
        'MANGA 3/4-2',
        'CUELLO V-1',
        'CUELLO REDONDO-1',
        'ESCOTE CRUZADO (WRAP)-1',
        'PLUNGE (ESCOTADO)-1',
        'CUELLO BOTE-1',
        'JACQUARD-5',
        'BLUE JEAN-5',
        'TENCEL-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'LINO-5',
        'ALGODON-5',
        'OTRA-5',
        'CHEVRON (ZIGZAG)-6',
        'FLORES-6',
        'TIE DYE-6',
        'PAISLEY-6',
        'LISO-6',
        'ENCAJE-12',
        'FLECOS-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'OJETILLOS-12',
        'CORDON/TIRA-12',
        'NINGUNO-12',
        'CINTURON-12',
        'ACANALADO-12',
        'NIDO ABEJA-12',
        'OTRO-12',
      ],
      'SWEATERS (CERRADOS)': [
        'CROP-3',
        'NORMAL-3',
        'LARGO-3',
        'MANGA LARGA - CLASICA-2',
        'MANGA LARGA - FLARE-2',
        'COLD SHOULDER-2',
        'MANGA 3/4-2',
        'SUELTO-4',
        'NORMAL-4',
        'OVERSIZE-4',
        'CUELLO V-1',
        'CUELLO REDONDO-1',
        'PLUNGE (ESCOTADO)-1',
        'CUELLO BOTE-1',
        'TERCIOPELO-5',
        'PLUSH-5',
        'GAMUZA-5',
        'ALGODON-5',
        'LANA-5',
        'HILO-5',
        'OTRA-5',
        'CHEVRON (ZIGZAG)-6',
        'FLORES-6',
        'TIE DYE-6',
        'PAISLEY-6',
        'LISO-6',
        'ENCAJE-12',
        'FLECOS-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'CORDON/TIRA-12',
        'OJETILLOS-12',
      ],
      'SWEATERS (ABIERTOS)': [
        'CROP-3',
        'NORMAL-3',
        'LARGO-3',
        'MANGA LARGA - CLASICA-2',
        'MANGA LARGA - FLARE-2',
        'COLD SHOULDER-2',
        'MANGA 3/4-2',
        'CUELLO V-1',
        'CUELLO REDONDO-1',
        'PLUNGE (ESCOTADO)-1',
        'TERCIOPELO-5',
        'PLUSH-5',
        'GAMUZA-5',
        'ALGODON-5',
        'LANA-5',
        'HILO-5',
        'OTRA-5',
        'CHEVRON (ZIGZAG)-6',
        'FLORES-6',
        'TIE DYE-6',
        'PAISLEY-6',
        'LISO-6',
        'ENCAJE-12',
        'FLECOS-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'CORDON/TIRA-12',
        'OJETILLOS-12',
        'BOTONES-12', ##
      ],
      'POLERONES (ABIERTOS O CERRADOS)': [
        'CROP-3',
        'NORMAL-3',
        'LARGO-3',
        'MANGA LARGA- CLASICA-2',
        'UNA MANGA-2',
        'MANGA CORTA - CLASICA-2',
        'OFF SHOULDER-2',
        'COLD SHOULDER-2',
        'CUELLO V-1',
        'CUELLO REDONDO-1',
        'CUELLO BOTE-1',
        'ALGODON-5',
        'OTRA-5',
        'CHEVRON (ZIGZAG)-6',
        'FLORES-6',
        'TIE DYE-6',
        'PAISLEY-6',
        'LISO-6',
        'ENCAJE-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
      ],
      'JEANS': [
        'ALTO (HIGH RISE)-8',
        'NORMAL (A LA CINTURA)-8',
        'LOW RISE (CORTE BAJO)-8',
        'CULOTTE (PANTORILLA)-7',
        'CROP (TOBILLO)-7',
        'REGULAR-7',
        'FLARE-9',
        'PITILLO (SKINNY)-9',
        'WIDE-9',
        'CORTE BOTA-9',
        'OTRO-9',
        'BLUE JEAN-5',
        'CHEVRON (ZIGZAG)-6',
        'FLORES-6',
        'TIE DYE-6',
        'PAISLEY-6',
        'LISO-6',
        'FLECOS-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'NUDO-12',
        'OJETILLOS-12',
        'ACID WASH-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'PANTALONES': [
        'ALTO (HIGH RISE)-8',
        'NORMAL (A LA CINTURA)-8',
        'LOW RISE (CORTE BAJO)-8',
        'CULOTTE (PANTORILLA)-7',
        'CROP (TOBILLO)-7',
        'REGULAR-7',
        'FLARE-9',
        'PITILLO (SKINNY)-9',
        'WIDE-9',
        'CORTE BOTA-9',
        'OTRO-9',
        'JACQUARD-5',
        'TENCEL-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'LINO-5',
        'GAMUZA-5',
        'CUERO-5',
        'ECO CUERO-5',
        'COTELE-5',
        'PLISADO-5',
        'LANA-5',
        'HILO-5',
        'OTRA-5',
        'CHEVRON (ZIGZAG)-6',
        'FLORES-6',
        'TIE DYE-6',
        'PAISLEY-6',
        'LISO-6',
        'FLECOS-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'NUDO-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'SHORTS': [
        'ALTO (HIGH RISE)-8',
        'NORMAL (A LA CINTURA)-8',
        'LOW RISE (CORTE BAJO)-8',
        'CORTO-14',
        'NORMAL-14',
        'BERMUDA-14',
        'JACQUARD-5',
        'BLUE JEAN-5',
        'TENCEL-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'LINO-5',
        'GAMUZA-5',
        'ALGODON-5',
        'GABARDINA-5',
        'CUERO-5',
        'ECO CUERO-5',
        'COTELE-5',
        'PLISADO-5',
        'LANA-5',
        'HILO-5',
        'BRODERIE-5',
        'OTRA-5',
        'CHEVRON (ZIGZAG)-6',
        'FLORES-6',
        'TIE DYE-6',
        'PAISLEY-6',
        'LISO-6',
        'FLECOS-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'NUDO-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'FALDAS': [
        'MINI-15',
        'MIDI-15',
        'MAXI-15',
        'DESIGUAL-15',
        'JACQUARD-5',
        'BLUE JEAN-5',
        'TENCEL-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'LINO-5',
        'GAMUZA-5',
        'ALGODON-5',
        'CUERO-5',
        'ECO CUERO-5',
        'COTELE-5',
        'PLISADO-5',
        'LANA-5',
        'HILO-5',
        'BRODERIE-5',
        'OTRA-5',
        'CHEVRON (ZIGZAG)-6',
        'FLORES-6',
        'TIE DYE-6',
        'PAISLEY-6',
        'LISO-6',
        'ENCAJE-12',
        'FLECOS-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'NUDO-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'SKORTS': [
        'JACQUARD-5',
        'BLUE JEAN-5',
        'TENCEL-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'LINO-5',
        'GAMUZA-5',
        'ALGODON-5',
        'CUERO-5',
        'ECO CUERO-5',
        'COTELE-5',
        'BRODERIE-5',
        'OTRA-5',
        'CHEVRON (ZIGZAG)-6',
        'FLORES-6',
        'TIE DYE-6',
        'PAISLEY-6',
        'LISO-6',
        'TROPICAL-6',
        'OTRO-6',
        'ENCAJE-12',
        'FLECOS-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'OTRO-12',
        'NINGUNO-12',
      ]
    }
  end

  def rock_seeds
    {
      'BLUSAS': [
        'CROP-3',
        'NORMAL-3',
        'LARGO-3',
        'STRAPLESS-2',
        'MANGA LARGA - CLASICA-2',
        'MANGA CORTA - CLASICA-2',
        'UNA MANGA-2',
        'SIN MANGA-2',
        'TIRITAS-2',
        'COLD SHOULDER-2',
        'MANGA 3/4-2',
        'STRAPLESS-1',
        'CUELLO V-1',
        'CUELLO REDONDO-1',
        'CUADRADO-1',
        'PLUNGE (ESCOTADO)-1',
        'BLUE JEAN-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'GAMUZA-5',
        'ALGODON-5',
        'GABARDINA-5',
        'FRANELA-5',
        'CUERO-5',
        'ECO CUERO-5',
        'COTELE-5',
        'LYCRA-5',
        'RIBBED-5',
        'WAFFLE-5',
        'LANA-5',
        'HILO-5',
        'OTRA-5',
        'TIE DYE-6',
        'ANIMAL PRINT-6',
        'GINHAM-6',
        'PRINCIPE DE GALES-6',
        'CAMUFLADO-6',
        'LISO-6',
        'OTRO-6',
        'FLECOS-12',
        'TACHAS-12',
        'DESTROY-12',
        'LENTEJUELAS-12',
        'NUDO-12',
        'TRANSPARENCIA-12',
        'OJETILLOS-12',
        'CORDON/TIRA-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'POLERAS': [
        'CROP-3',
        'NORMAL-3',
        'LARGO-3',
        'STRAPLESS-2',
      'MANGA LARGA - CLASICA-2',
      'MANGA CORTA - CLASICA-2',
      'UNA MANGA-2',
      'SIN MANGA-2',
      'TIRITAS-2',
      'COLD SHOULDER-2',
      'MANGA 3/4-2',
      'APRETADO-4',
      'SUELTO-4',
      'NORMAL-4',
      'OVERSIZE-4',
      'STRAPLESS-1',
      'CUELLO V-1',
      'CUELLO REDONDO-1',
      'CUADRADO-1',
      'PLUNGE (ESCOTADO)-1',
      'CUELLO ALTO (BEATLE)-1',
      'BLUE JEAN-5',
      'TERCIOPELO-5',
      'PLUSH-5',
      'GAMUZA-5',
      'ALGODON-5',
      'GABARDINA-5',
      'FRANELA-5',
      'CUERO-5',
      'ECO CUERO-5',
      'COTELE-5',
      'LYCRA-5',
      'RIBBED-5',
      'WAFFLE-5',
      'LANA-5',
      'HILO-5',
      'OTRA-5',
      'TIE DYE-6',
      'ANIMAL PRINT-6',
      'GINHAM-6',
      'PRINCIPE DE GALES-6',
      'CAMUFLADO-6',
      'LISO-6',
      'OTRO-6',
      'FLECOS-12',
      'TACHAS-12',
      'DESTROY-12',
      'LENTEJUELAS-12',
      'NUDO-12',
      'TRANSPARENCIA-12',
      'OJETILLOS-12',
      'CORDON/TIRA-12',
      'OTRO-12',
      'NINGUNO-12',
      ],
      'BODYS': [
        'MANGA LARGA - CLASICA-2',
      'MANGA CORTA - CLASICA-2',
      'UNA MANGA-2',
      'SIN MANGA-2',
      'TIRITAS-2',
      'COLD SHOULDER-2',
      'CUELLO V-1',
      'CUELLO REDONDO-1',
      'CUADRADO-1',
      'PLUNGE (ESCOTADO)-1',
      'CUELLO ALTO (BEATLE)-1',
      'BLUE JEAN-5',
      'TERCIOPELO-5',
      'PLUSH-5',
      'GAMUZA-5',
      'ALGODON-5',
      'GABARDINA-5',
      'CUERO-5',
      'ECO CUERO-5',
      'COTELE-5',
      'LYCRA-5',
      'RIBBED-5',
      'WAFFLE-5',
      'LANA-5',
      'HILO-5',
      'OTRA-5',
      'TIE DYE-6',
      'ANIMAL PRINT-6',
      'GINHAM-6',
      'PRINCIPE DE GALES-6',
      'CAMUFLADO-6',
      'LISO-6',
      'OTRO-6',
      'FLECOS-12',
      'TACHAS-12',
      'DESTROY-12',
      'LENTEJUELAS-12',
      'NUDO-12',
      'TRANSPARENCIA-12',
      'OJETILLOS-12',
      'CORDON/TIRA-12',
      'OTRO-12',
      'NINGUNO-12',
      ],
      'ABRIGOS': [
        'CROP-3',
        'MEDIO-3',
        'TOBILLO-3',
        'LARGO-3',
        'SIN MANGA-2',
        'MANGA CORTA-2',
        'MANGA LARGA-2',
        'APRETADO-4',
        'SUELTO-4',
        'NORMAL-4',
        'OVERSIZE-4',
        'BLUE JEAN-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'GAMUZA-5',
        'ALGODON-5',
        'GABARDINA-5',
        'FRANELA-5',
        'CUERO-5',
        'ECO CUERO-5',
        'COTELE-5',
        'PIEL-5',
        'PIEL SINTETICA-5',
        'LANA-5',
        'HILO-5',
        'OTRA-5',
        'TIE DYE-6',
        'ANIMAL PRINT-6',
        'GINHAM-6',
        'PRINCIPE DE GALES-6',
        'CAMUFLADO-6',
        'LISO-6',
        'OTRO-6',
        'FLECOS-12',
        'TACHAS-12',
        'DESTROY-12',
        'LENTEJUELAS-12',
        'NUDO-12',
        'TRANSPARENCIA-12',
        'OJETILLOS-12',
        'CORDON/TIRA-12',
        'OTRO-12',
        'NINGUNO-12',
      ], 
      'BOMBER': [
        'POLIESTER-5',
        'ALGODON-5',
        'OTRA-5',
        'TIE DYE-6',
        'ANIMAL PRINT-6',
        'GINHAM-6',
        'PRINCIPE DE GALES-6',
        'CAMUFLADO-6',
        'LISO-6',
        'OTRO-6',
      ],
      'CHAQUETAS': [
        'CROP-3',
        'MEDIO-3',
        'TOBILLO-3',
        'LARGO-3',
        'SIN MANGA-2',
        'MANGA CORTA-2',
        'MANGA LARGA-2',
        'APRETADO-4',
        'SUELTO-4',
        'NORMAL-4',
        'OVERSIZE-4',
        'BLUE JEAN-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'GAMUZA-5',
        'ALGODON-5',
        'GABARDINA-5',
        'FRANELA-5',
        'CUERO-5',
        'ECO CUERO-5',
        'COTELE-5',
        'PIEL-5',
        'PIEL SINTETICA-5',
        'LANA-5',
        'HILO-5',
        'OTRA-5',
        'TIE DYE-6',
        'ANIMAL PRINT-6',
        'GINHAM-6',
        'PRINCIPE DE GALES-6',
        'CAMUFLADO-6',
        'LISO-6',
        'OTRO-6',
        'FLECOS-12',
        'TACHAS-12',
        'DESTROY-12',
        'LENTEJUELAS-12',
        'NUDO-12',
        'TRANSPARENCIA-12',
        'OJETILLOS-12',
        'CORDON/TIRA-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'PARKAS': [
        'MEDIO-3',
        'TOBILLO-3',
        'LARGO-3',
        'PARKA-5',
        'TIE DYE-6',
        'ANIMAL PRINT-6',
        'CAMUFLADO-6',
        'LISO-6',
        'OTRO-6',
      ],
      'VESTIDO': [
        'MINI-15',
        'MIDI-15',
        'MAXI-15',
        'DESIGUAL-15',
        'STRAPLESS-2',
        'MANGA LARGA - CLASICA-2',
        'MANGA CORTA - CLASICA-2',
        'UNA MANGA-2',
        'SIN MANGA-2',
        'TIRITAS-2',
        'COLD SHOULDER-2',
        'MANGA 3/4-2',
        'BLAZER-16',
        'BODYCON (AJUSTADO)-16',
        'CUT OUT-16',
        'POLERA-16',
        'SKATER-16',
        'SLIP-16',
        'STRAPLESS-1',
        'CUELLO V-1',
        'CUELLO REDONDO-1',
        'STRAPLESS-1',
        'CUADRADO-1',
        'PLUNGE (ESCOTADO)-1',
        'CUELLO BOTE-1',
        'BLUE JEAN-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'GAMUZA-5',
        'ALGODON-5',
        'GABARDINA-5',
        'FRANELA-5',
        'CUERO-5',
        'ECO CUERO-5',
        'COTELE-5',
        'RIBBED-5',
        'WAFFLE-5',
        'LANA-5',
        'HILO-5',
        'OTRA-5',
        'TIE DYE-6',
        'ANIMAL PRINT-6',
        'GINHAM-6',
        'PRINCIPE DE GALES-6',
        'CAMUFLADO-6',
        'LISO-6',
        'OTRO-6',
        'FLECOS-12',
        'TACHAS-12',
        'DESTROY-12',
        'LENTEJUELAS-12',
        'MOSTACILLAS-12',
        'NUDO-12',
        'TRANSPARENCIA-12',
        'OJETILLOS-12',
        'CORDON/TIRA-12',
        'CINTURON-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'ENTERITOS': [
        'MINI-15',
        'MIDI-15',
        'MAXI-15',
        'STRAPLESS-2',
        'MANGA LARGA - CLASICA-2',
        'MANGA CORTA - CLASICA-2',
        'UNA MANGA-2',
        'SIN MANGA-2',
        'TIRITAS-2',
        'COLD SHOULDER-2',
        'MANGA 3/4-2',
        'STRAPLESS-1',
        'CUELLO V-1',
        'CUELLO REDONDO-1',
        'STRAPLESS-1',
        'CUADRADO-1',
        'PLUNGE (ESCOTADO)-1',
        'BLUE JEAN-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'GAMUZA-5',
        'ALGODON-5',
        'GABARDINA-5',
        'FRANELA-5',
        'CUERO-5',
        'ECO CUERO-5',
        'COTELE-5',
        'RIBBED-5',
        'WAFFLE-5',
        'LANA-5',
        'HILO-5',
        'OTRA-5',
        'TIE DYE-6',
        'ANIMAL PRINT-6',
        'GINHAM-6',
        'PRINCIPE DE GALES-6',
        'CAMUFLADO-6',
        'LISO-6',
        'OTRO-6',
        'FLECOS-12',
        'TACHAS-12',
        'DESTROY-12',
        'LENTEJUELAS-12',
        'MOSTACILLAS-12',
        'NUDO-12',
        'TRANSPARENCIA-12',
        'OJETILLOS-12',
        'CORDON/TIRA-12',
        'CINTURON-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'SWEATERS (CERRADOS)': [
        'CROP-3',
        'NORMAL-3',
        'LARGO-3',
        'MANGA LARGA - CLASICA-2',
        'MANGA LARGA - FLARE-2',
        'COLD SHOULDER-2',
        'MANGA 3/4-2',
        'SUELTO-4',
        'NORMAL-4',
        'OVERSIZE-4',
        'CUELLO V-1',
        'CUELLO REDONDO-1',
        'PLUNGE (ESCOTADO)-1',
        'CUELLO BOTE-1',
        'TERCIOPELO-5',
        'PLUSH-5',
        'GAMUZA-5',
        'ALGODON-5',
        'LANA-5',
        'HILO-5',
        'OTRA-5',
        'CHEVRON (ZIGZAG)-6',
        'FLORES-6',
        'TIE DYE-6',
        'PAISLEY-6',
        'LISO-6',
        'ENCAJE-12',
        'FLECOS-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'CORDON/TIRA-12',
        'OJETILLOS-12',
      ],
      'SWEATERS (ABIERTOS)': [
        'CROP-3',
        'NORMAL-3',
        'LARGO-3',
        'MANGA LARGA - CLASICA-2',
        'MANGA 3/4-2',
        'CUELLO V-1',
        'CUELLO REDONDO-1',
        'ESCOTE CRUZADO (WRAP)-1',
        'ALGODON-5',
        'LANA-5',
        'HILO-5',
        'OTRA-5',
        'TIE DYE-6',
        'ANIMAL PRINT-6',
        'CAMUFLADO-6',
        'GINHAM-6',
        'LISO-6',
        'OTRO-6',
        'FLECOS-12',
        'TACHAS-12',
        'DESTROY-12',
        'LENTEJUELAS-12',
        'MOSTACILLAS-12',
        'NUDO-12',
        'OJETILLOS-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'POLERONES (ABIERTOS O CERRADOS)': [
        'CROP-3',
        'NORMAL-3',
        'LARGO-3',
        'MANGA LARGA - CLASICA-2',
        'CUELLO V-1',
        'CUELLO REDONDO-1',
        'ALGODON-5',
        'OTRA-5',
        'TIE DYE-6',
        'ANIMAL PRINT-6',
        'CAMUFLADO-6',
        'LISO-6',
        'OTRO-6',
        'FLECOS-12',
        'TACHAS-12',
        'DESTROY-12',
        'LENTEJUELAS-12',
        'MOSTACILLAS-12',
        'OJETILLOS-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'JEANS': [
        'ALTO (HIGH RISE)-8',
        'NORMAL (A LA CINTURA)-8',
        'LOW RISE (CORTE BAJO)-8',
        'CROP (TOBILLO)-7',
        'REGULAR-7',
        'PITILLO (SKINNY)-9',
        'BOYFRIEND-9',
        'MOM-9',
        'OTRO-9',
        'BLUE JEAN-5',
        'TIE DYE-6',
        'ANIMAL PRINT-6',
        'CAMUFLADO-6',
        'LISO-6',
        'OTRO-6',
        'TACHAS-12',
        'DESTROY-12',
        'LENTEJUELAS-12',
        'MOSTACILLAS-12',
        'OJETILLOS-12',
        'ACID WASH-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'PANTALONES': [
        'ALTO (HIGH RISE)-8',
        'NORMAL (A LA CINTURA)-8',
        'LOW RISE (CORTE BAJO)-8',
        'CROP (TOBILLO)-7',
        'REGULAR-7',
        'PITILLO (SKINNY)-9',
        'BOYFRIEND-9',
        'MOM-9',
        'OTRO-9',
        'TERCIOPELO-5',
        'PLUSH-5',
        'GAMUZA-5',
        'ALGODON-5',
        'CUERO-5',
        'ECO CUERO-5',
        'COTELE-5',
        'OTRA-5',
        'TIE DYE-6',
        'ANIMAL PRINT-6',
        'CAMUFLADO-6',
        'GINHAM-6',
        'PRINCIPE DE GALES-6',
        'LISO-6',
        'OTRO-6',
        'TACHAS-12',
        'DESTROY-12',
        'LENTEJUELAS-12',
        'MOSTACILLAS-12',
        'OJETILLOS-12',
        'ACID WASH-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'PATAS': [
        'NORMAL (A LA CINTURA)-8',
        'REGULAR-7',
        'RECTO-9',
        'JOGGER-9',
        'TERCIOPELO-5',
        'PLUSH-5',
        'GAMUZA-5',
        'ALGODON-5',
        'CUERO-5',
        'ECO CUERO-5',
        'OTRA-5',
        'TIE DYE-6',
        'ANIMAL PRINT-6',
        'CAMUFLADO-6',
        'LISO-6',
        'OTRO-6',
        'TACHAS-12',
        'LENTEJUELAS-12',
        'MOSTACILLAS-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'JOGGERS': [
        'NORMAL (A LA CINTURA)-8',
        'REGULAR-7',
        'JOGGER-9',
        'TIE DYE-6',
        'ANIMAL PRINT-6',
        'CAMUFLADO-6',
        'LISO-6',
        'OTRO-6',
      ],
      'SHORTS': [
        'ALTO (HIGH RISE)-8',
        'NORMAL (A LA CINTURA)-8',
        'LOW RISE (CORTE BAJO)-8',
        'CORTO-14',
        'NORMAL-14',
        'BLUE JEAN-5',
        'GAMUZA-5',
        'ALGODON-5',
        'CUERO-5',
        'ECO CUERO-5',
        'COTELE-5',
        'OTRA-5',
        'TIE DYE-6',
        'ANIMAL PRINT-6',
        'CAMUFLADO-6',
        'GINHAM-6',
        'PRINCIPE DE GALES-6',
        'LISO-6',
        'OTRO-6',
        'TACHAS-12',
        'DESTROY-12',
        'LENTEJUELAS-12',
        'MOSTACILLAS-12',
        'OJETILLOS-12',
        'ACID WASH-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'FALDAS': [
        'MINI-15',
        'MIDI-15',
        'MAXI-15',
        'BLUE JEAN-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'GAMUZA-5',
        'ALGODON-5',
        'CUERO-5',
        'ECO CUERO-5',
        'COTELE-5',
        'LANA-5',
        'HILO-5',
        'OTRA-5',
        'TIE DYE-6',
        'ANIMAL PRINT-6',
        'GINHAM-6',
        'PRINCIPE DE GALES-6',
        'CAMUFLADO-6',
        'LISO-6',
        'OTRO-6',
        'TACHAS-12',
        'DESTROY-12',
        'LENTEJUELAS-12',
        'MOSTACILLAS-12',
        'OJETILLOS-12',
        'ACID WASH-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'SKORTS': [
        'BLUE JEAN-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'GAMUZA-5',
        'ALGODON-5',
        'CUERO-5',
        'ECO CUERO-5',
        'COTELE-5',
        'OTRA-5',
        'TIE DYE-6',
        'ANIMAL PRINT-6',
        'GINHAM-6',
        'PRINCIPE DE GALES-6',
        'CAMUFLADO-6',
        'LISO-6',
        'OTRO-6',
        'FLECOS-12',
        'TACHAS-12',
        'DESTROY-12',
        'LENTEJUELAS-12',
        'MOSTACILLAS-12',
        'TRANSPARENCIA-12',
        'OJETILLOS-12',
        'ACID WASH-12',
        'OTRO-12',
        'NINGUNO-12',
      ]
    }
  end

  def clasico_seeds
    {
      'BLUSAS': [
        'NORMAL-3',
        'LARGO-3',
        'MANGA LARGA - CLASICA-2',
        'MANGA CORTA - CLASICA-2',
        'SIN MANGA-2',
        'MANGA 3/4-2',
        'NORMAL-4',
        'CUELLO V-1',
        'CUELLO REDONDO-1',
        'ESCOTE CRUZADO (WRAP)-1',
        'CUELLO SUBIDO (BEATLE)-1',
        'OTRO-1',
        'BLUE JEAN-5',
        'TENCEL-5',
        'LINO-5',
        'GAMUZA-5',
        'ALGODON-5',
        'POPELINA-5',
        'BRODERIE-5',
        'OTRA-5',
        'FLORES-6',
        'TIE DYE-6',
        'PAISLEY-6',
        'ANIMAL PRINT-6',
        'CAMUFLADO-6',
        'RAYAS-6',
        'TROPICAL-6',
        'LISO-6',
        'OTRO-6',
        'DESTROY-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'CINTA-12',
        'NUDO-12',
        'CORDON/TIRA-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'POLERAS': [
        'NORMAL-3',
        'LARGO-3',
        'MANGA LARGA - CLASICA-2',
        'MANGA CORTA - CLASICA-2',
        'SIN MANGA-2',
        'TIRITAS-2',
        'MANGA 3/4-2',
        'SUELTO-4',
        'NORMAL-4',
        'CUELLO V-1',
        'CUELLO REDONDO-1',
        'ESCOTE CRUZADO (WRAP)-1',
        'CINTA-1',
        'CUELLO SUBIDO (BEATLE)-1',
        'OTRO-1',
        'TENCEL-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'LINO-5',
        'GAMUZA-5',
        'ALGODON-5',
        'POPELINA-5',
        'BRODERIE-5',
        'CROCHET-5',
        'RIBBED-5',
        'WAFFLE-5',
        'HILO-5',
        'OTRA-5',
        'FLORES-6',
        'PAISLEY-6',
        'ANIMAL PRINT-6',
        'CAMUFLADO-6',
        'RAYAS-6',
        'PUNTOS-6',
        'TROPICAL-6',
        'LISO-6',
        'OTRO-6',
        'ENCAJE-12',
        'TACHAS-12',
        'DESTROY-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'CINTA-12',
        'NUDO-12',
        'TRANSPARENCIA-12',
        'CORDON/TIRA-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'BODYS': [
        'NORMAL-3',
        'MANGA LARGA - CLASICA-2',
        'MANGA LARGA - FLARE-2',
        'MANGA CORTA - MURCIELAGO-2',
        'MANGA CORTA - FLARE-2',
        'MANGA CORTA - CLASICA-2',
        'SIN MANGA-2',
        'TIRITAS-2',
        'SUELTO-4',
        'NORMAL-4',
        'CUELLO V-1',
        'CUELLO REDONDO-1',
        'ESCOTE CRUZADO (WRAP)-1',
        'OTRO-1',
        'ALGODON-5',
        'LYCRA-5',
        'OTRA-5',
        'FLORES-6',
        'PAISLEY-6',
        'ANIMAL PRINT-6',
        'CAMUFLADO-6',
        'RAYAS-6',
        'PUNTOS-6',
        'TROPICAL-6',
        'LISO-6',
        'OTRO-6',
        'ENCAJE-12',
        'TACHAS-12',
        'DESTROY-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'CINTA-12',
        'NUDO-12',
        'TRANSPARENCIA-12',
        'CORDON/TIRA-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'ABRIGOS': [
        'MEDIO-3',
        'LARGO-3',
        'MANGA LARGA - CLASICA-2',
        'SUELTO-4',
        'NORMAL-4',
        'TERCIOPELO-5',
        'PLUSH-5',
        'LINO-5',
        'GAMUZA-5',
        'ALGODON-5',
        'GABARDINA-5',
        'COTELE-5',
        'PIEL-5',
        'PIEL SINTETICA-5',
        'LANA-5',
        'HILO-5',
        'OTRA-5',
        'FLORES-6',
        'PAISLEY-6',
        'ANIMAL PRINT-6',
        'LISO-6',
        'OTRO-6',
        'TROPICAL-6',
        'TACHAS-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'OTRO-12',
        'NINGUNO-12',
      ], 
      'BLAZER': [
        'MEDIO-3',
        'MANGA LARGA - CLASICA-2',
        'NORMAL-4',
        'TENCEL-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'LINO-5',
        'GAMUZA-5',
        'ALGODON-5',
        'COTELE-5',
        'OTRA-5',
        'RAYAS-6',
        'LISO-6',
        'OTRO-6',
        'TROPICAL-6',
        'TACHAS-12',
        'DESTROY-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'CHAQUETAS': [
        'MEDIO-3',
        'MANGA LARGA - CLASICA-2',
        'SUELTO-4',
        'NORMAL-4',
        'BLUE JEAN-5',
        'TENCEL-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'LINO-5',
        'GAMUZA-5',
        'ALGODON-5',
        'GABARDINA-5',
        'COTELE-5',
        'OTRA-5',
        'FLORES-6',
        'PAISLEY-6',
        'ANIMAL PRINT-6',
        'CAMUFLADO-6',
        'RAYAS-6',
        'LISO-6',
        'OTRO-6',
        'TROPICAL-6',
        'TACHAS-12',
        'DESTROY-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'PARKAS': [
        'MEDIO-3',
        'LARGO-3',
        'PARKA-5',
        'LISO-6',
        'NINGUNO-12',
      ],
      'VESTIDO': [
        'MINI-15',
        'MAXI-15',
        'MANGA LARGA - CLASICA-2',
        'MANGA LARGA - FLARE-2',
        'MANGA CORTA - FLARE-2',
        'MANGA CORTA - CLASICA-2',
        'SIN MANGA-2',
        'TIRITAS-2',
        'MANGA 3/4-2',
        'FORMA A-16',
        'BLAZER-16',
        'POLERA-16',
        'SKATER-16',
        'SLIP-16',
        'SMOCK-16',
        'WRAP-16',
        'CORTE IMPERIO (ABAJO PECHUGA)-16',
        'SHIFT-16',
        'CUELLO V-1',
        'CUELLO REDONDO-1',
        'ESCOTE CRUZADO (WRAP)-1',
        'CINTA-1',
        'CUELLO BOTE-1',
        'OTRO-1',
        'BLUE JEAN-5',
        'TENCEL-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'LINO-5',
        'GAMUZA-5',
        'ALGODON-5',
        'BRODERIE-5',
        'FLORES-6',
        'TIE DYE-6',
        'PAISLEY-6',
        'ANIMAL PRINT-6',
        'CAMUFLADO-6',
        'RAYAS-6',
        'TROPICAL-6',
        'LISO-6',
        'OTRO-6',
        'ENCAJE-12',
        'TACHAS-12',
        'DESTROY-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'CINTA-12',
        'NUDO-12',
        'CORDON/TIRA-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'ENTERITOS': [
        'MINI-15',
        'MAXI-15',
        'MANGA LARGA - CLASICA-2',
        'MANGA LARGA - FLARE-2',
        'MANGA CORTA - FLARE-2',
        'MANGA CORTA - CLASICA-2',
        'SIN MANGA-2',
        'TIRITAS-2',
        'MANGA 3/4-2',
        'CUELLO V-1',
        'CUELLO REDONDO-1',
        'ESCOTE CRUZADO (WRAP)-1',
        'CINTA-1',
        'CUELLO BOTE-1',
        'OTRO-1',
        'BLUE JEAN-5',
        'TENCEL-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'LINO-5',
        'GAMUZA-5',
        'ALGODON-5',
        'BRODERIE-5',
        'FLORES-6',
        'TIE DYE-6',
        'PAISLEY-6',
        'ANIMAL PRINT-6',
        'CAMUFLADO-6',
        'RAYAS-6',
        'TROPICAL-6',
        'LISO-6',
        'OTRO-6',
        'ENCAJE-12',
        'TACHAS-12',
        'DESTROY-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'CINTA-12',
        'NUDO-12',
        'CORDON/TIRA-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'SWEATERS (CERRADOS)': [
        'NORMAL-3',
        'LARGO-3',
        'MANGA LARGA - CLASICA-2',
        'MANGA LARGA - FLARE-2',
        'MANGA 3/4-2',
        'NORMAL-4',
        'CUELLO V-1',
        'CUELLO REDONDO-1',
        'CINTA-1',
        'CUELLO BOTE-1',
        'OTRO-1',
        'ALGODON-5',
        'LANA-5',
        'HILO-5',
        'OTRA-5',
        'FLORES-6',
        'TIE DYE-6',
        'PAISLEY-6',
        'ANIMAL PRINT-6',
        'CAMUFLADO-6',
        'RAYAS-6',
        'TROPICAL-6',
        'LISO-6',
        'OTRO-6',
        'ENCAJE-12',
        'TACHAS-12',
        'DESTROY-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'CINTA-12',
        'NUDO-12',
        'CORDON/TIRA-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'SWEATERS (ABIERTOS)': [
        'NORMAL-3',
        'LARGO-3',
        'MANGA LARGA - CLASICA-2',
        'MANGA 3/4-2',
        'NORMAL-4',
        'CUELLO V-1',
        'CUELLO REDONDO-1',
        'ESCOTE CRUZADO (WRAP)-1',
        'CINTA-1',
        'CUELLO BOTE-1',
        'OTRO-1',
        'ALGODON-5',
        'LANA-5',
        'HILO-5',
        'OTRA-5',
        'FLORES-6',
        'TIE DYE-6',
        'PAISLEY-6',
        'ANIMAL PRINT-6',
        'CAMUFLADO-6',
        'RAYAS-6',
        'TROPICAL-6',
        'LISO-6',
        'OTRO-6',
        'ENCAJE-12',
        'TACHAS-12',
        'DESTROY-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'CINTA-12',
        'NUDO-12',
        'CORDON/TIRA-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'POLERONES (ABIERTOS O CERRADOS)': [
        'NORMAL-3',
        'MANGA LARGA - CLASICA-2',
        'NORMAL-4',
        'CUELLO V-1',
        'CUELLO REDONDO-1',
        'CUELLO BOTE-1',
        'OTRO-1',
        'ALGODON-5',
        'OTRA-5',
        'FLORES-6',
        'TIE DYE-6',
        'PAISLEY-6',
        'ANIMAL PRINT-6',
        'CAMUFLADO-6',
        'RAYAS-6',
        'TROPICAL-6',
        'LISO-6',
        'OTRO-6',
        'ENCAJE-12',
        'TACHAS-12',
        'DESTROY-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'CINTA-12',
        'NUDO-12',
        'CORDON/TIRA-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'JEANS': [
        'ALTO (HIGH RISE)-8',
        'NORMAL (A LA CINTURA)-8',
        'CULOTTE (PANTORILLA)-7',
        'CROP (T[OBILLO)-7',
        'REGULAR-7',
        'FLARE-9',
        'RECTO-9',
        'PITILLO (SKINNY)-9',
        'WIDE-9',
        'CORTE BOTA-9',
        'OTRO-9',
        'BLUE JEAN-5',
        'TIE DYE-6',
        'ANIMAL PRINT-6',
        'CAMUFLADO-6',
        'LISO-6',
        'OTRO-6',
        'TACHAS-12',
        'DESTROY-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'ACID WASH-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'PANTALONES': [
        'ALTO (HIGH RISE)-8',
        'NORMAL (A LA CINTURA)-8',
        'CULOTTE (PANTORILLA)-7',
        'CROP (TOBILLO)-7',
        'REGULAR-7',
        'FLARE-9',
        'RECTO-9',
        'PITILLO (SKINNY)-9',
        'WIDE-9',
        'CORTE BOTA-9',
        'OTRO-9',
        'TENCEL-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'LINO-5',
        'GAMUZA-5',
        'ALGODON-5',
        'COTELE-5',
        'PLISADO-5',
        'OTRA-5',
        'BLUE JEAN-5',
        'FLORES-6',
        'TIE DYE-6',
        'PAISLEY-6',
        'ANIMAL PRINT-6',
        'CAMUFLADO-6',
        'RAYAS-6',
        'LISO-6',
        'OTRO-6',
        'TROPICAL-6',
        'TACHAS-12',
        'DESTROY-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'SHORTS': [
        'ALTO (HIGH RISE)-8',
        'NORMAL (A LA CINTURA)-8',
        'CORTO-14',
        'NORMAL-14',
        'BERMUDA-14',
        'BLUE JEAN-5',
        'JACQUARD-5',
        'TENCEL-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'LINO-5',
        'GAMUZA-5',
        'ALGODON-5',
        'COTELE-5',
        'BRODERIE-5',
        'OTRA-5',
        'FLORES-6',
        'TIE DYE-6',
        'PAISLEY-6',
        'ANIMAL PRINT-6',
        'CAMUFLADO-6',
        'RAYAS-6',
        'LISO-6',
        'OTRO-6',
        'TROPICAL-6',
        'ENCAJE-12',
        'TACHAS-12',
        'DESTROY-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'CINTA-12',
        'NUDO-12',
        'CORDON/TIRA-12',
        'ACID WASH-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'FALDAS': [
        'MINI-15',
        'MAXI-15',
        'BLUE JEAN-5',
        'JACQUARD-5',
        'TENCEL-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'LINO-5',
        'GAMUZA-5',
        'ALGODON-5',
        'COTELE-5',
        'BRODERIE-5',
        'OTRA-5',
        'FLORES-6',
        'TIE DYE-6',
        'PAISLEY-6',
        'ANIMAL PRINT-6',
        'CAMUFLADO-6',
        'RAYAS-6',
        'LISO-6',
        'OTRO-6',
        'TROPICAL-6',
        'ENCAJE-12',
        'TACHAS-12',
        'DESTROY-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'CINTA-12',
        'NUDO-12',
        'CORDON/TIRA-12',
        'ACID WASH-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'SKORTS': [
        'JACQUARD-5',
        'BLUE JEAN-5',
        'TENCEL-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'LINO-5',
        'GAMUZA-5',
        'ALGODON-5',
        'COTELE-5',
        'BRODERIE-5',
        'OTRA-5',
        'FLORES-6',
        'TIE DYE-6',
        'PAISLEY-6',
        'ANIMAL PRINT-6',
        'CAMUFLADO-6',
        'RAYAS-6',
        'PUNTOS-6',
        'TROPICAL-6',
        'LISO-6',
        'OTRO-6',
        'ENCAJE-12',
        'FLECOS-12',
        'TACHAS-12',
        'DESTROY-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'ACID WASH-12',
        'OTRO-12',
        'NINGUNO-12',
      ]
    }
  end

  def romantico_seeds
    {
      'BLUSAS': [
        'NORMAL-3',
        'LARGO-3',
        'LARGA-3',
        'STRAPLESS-2',
        'MANGA LARGA - CLASICA-2',
        'MANGA LARGA - FLARE-2',
        'MANGA CORTA -GLOBO-2',
        'MANGA CORTA - MURCIELAGO-2',
        'MANGA CORTA - FLARE-2',
        'MANGA CORTA - CLASICA-2',
        'SIN MANGA-2',
        'TIRITAS-2',
        'OFF SHOULDER-2',
        'COLD SHOULDER-2',
        'MANGA 3/4-2',
        'APRETADO-4',
        'SUELTO-4',
        'NORMAL-4',
        'PEPLUM-4',
        'STRAPLESS-1',
        'CUELLO V-1',
        'CUELLO REDONDO-1',
        'ESCOTE CRUZADO (WRAP)-1',
        'CINTA-1',
        'CUADRADO-1',
        'ESCOTE CORAZÓN-1',
        'CUELLO BOTE-1',
        'OTRO-1',
        'PLUMETI-5',
        'JACQUARD-5',
        'BLUE JEAN-5',
        'TENCEL-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'LINO-5',
        'GAMUZA-5',
        'ALGODON-5',
        'CREPE-5',
        'ENCAJE-5',
        'POPELINA-5',
        'CHIFFON-5',
        'PLISADO-5',
        'BRODERIE-5',
        'CROCHET-5',
        'OTRA-5',
        'FLORES-6',
        'PAISLEY-6',
        'RAYAS-6',
        'PUNTOS-6',
        'TROPICAL-6',
        'LISO-6',
        'OTRO-6',
        'ENCAJE-12',
        'TULL-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'CINTA-12',
        'NUDO-12',
        'TRANSPARENCIA-12',
        'CORDON/TIRA-12',
        'ACANALADO-12',
        'NIDO ABEJA-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'POLERAS': [
        'CROP-3',
        'NORMAL-3',
        'LARGA-3',
        'STRAPLESS-2',
        'MANGA LARGA - CLASICA-2',
        'MANGA LARGA - FLARE-2',
        'MANGA CORTA -GLOBO-2',
        'MANGA CORTA - MURCIELAGO-2',
        'MANGA CORTA - FLARE-2',
        'MANGA CORTA - CLASICA-2',
        'SIN MANGA-2',
        'TIRITAS-2',
        'OFF SHOULDER-2',
        'COLD SHOULDER-2',
        'MANGA 3/4-2',
        'APRETADO-4',
        'SUELTO-4',
        'NORMAL-4',
        'PEPLUM-4',
        'STRAPLESS-1',
        'CUELLO V-1',
        'CUELLO REDONDO-1',
        'ESCOTE CRUZADO (WRAP)-1',
        'CINTA-1',
        'CUADRADO-1',
        'ESCOTE CORAZÓN-1',
        'CUELLO BOTE-1',
        'OTRO-1',
        'TERCIOPELO-5',
        'PLUSH-5',
        'LINO-5',
        'GAMUZA-5',
        'ALGODON-5',
        'ENCAJE-5',
        'LYCRA-5',
        'BRODERIE-5',
        'CROCHET-5',
        'RIBBED-5',
        'WAFFLE-5',
        'LANA-5',
        'HILO-5',
        'OTRA-5',
        'CHEVRON (ZIGZAG)-6',
        'FLORES-6',
        'PAISLEY-6',
        'RAYAS-6',
        'PUNTOS-6',
        'TROPICAL-6',
        'LISO-6',
        'OTRO-6',
        'ENCAJE-12',
        'TULL-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'CINTA-12',
        'NUDO-12',
        'TRANSPARENCIA-12',
        'CORDON/TIRA-12',
        'ACANALADO-12',
        'NIDO ABEJA-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'KIMONOS': [
        'MANGA LARGA - CLASICA-2',
        'MANGA CORTA - CLASICA-2',
        'PLUMETI-5',
        'JACQUARD-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'ALGODON-5',
        'ENCAJE-5',
        'OTRA-5',
        'CHEVRON (ZIGZAG)-6',
        'FLORES-6',
        'PAISLEY-6',
        'RAYAS-6',
        'PUNTOS-6',
        'TROPICAL-6',
        'LISO-6',
        'OTRO-6',
        'ENCAJE-12',
        'TULL-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'CINTA-12',
        'NUDO-12',
        'TRANSPARENCIA-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'ABRIGOS': [
        'CROP-3',
        'MEDIO-3',
        'TOBILLO-3',
        'LARGO-3',
        'MANGA LARGA - CLASICA-2',
        'NORMAL-4',
        'JACQUARD-5',
        'BLUE JEAN-5',
        'TENCEL-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'LINO-5',
        'GAMUZA-5',
        'ALGODON-5',
        'GABARDINA-5',
        'COTELE-5',
        'PIEL-5',
        'PIEL SINTETICA-5',
        'LANA-5',
        'OTRA-5',
        'CHEVRON (ZIGZAG)-6',
        'TIE DYE-6',
        'PAISLEY-6',
        'RAYAS-6',
        'PUNTOS-6',
        'TROPICAL-6',
        'LISO-6',
        'OTRO-6',
        'ENCAJE-12',
        'TULL-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'CINTA-12',
        'NUDO-12',
        'TRANSPARENCIA-12',
        'CINTURON-12',
        'OTRO-12',
        'NINGUNO-12',
      ], 
      'BLAZER': [
        'MEDIO-3',
        'MANGA LARGA - CLASICA-2',
        'NORMAL-4',
        'JACQUARD-5',
        'TENCEL-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'LINO-5',
        'GAMUZA-5',
        'ALGODON-5',
        'GABARDINA-5',
        'COTELE-5',
        'BRODERIE-5',
        'OTRA-5',
        'FLORES-6',
        'PAISLEY-6',
        'RAYAS-6',
        'PUNTOS-6',
        'TROPICAL-6',
        'LISO-6',
        'OTRO-6',
        'ENCAJE-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'CINTA-12',
        'NUDO-12',
        'TRANSPARENCIA-12',
        'CORDON/TIRA-12',
        'CINTURON-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'CHAQUETAS': [
        'CROP-3',
        'MEDIO-3',
        'TOBILLO-3',
        'LARGO-3',
        'MANGA LARGA - CLASICA-2',
        'NORMAL-4',
        'JACQUARD-5',
        'BLUE JEAN-5',
        'TENCEL-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'LINO-5',
        'GAMUZA-5',
        'ALGODON-5',
        'GABARDINA-5',
        'COTELE-5',
        'LANA-5',
        'OTRA-5',
        'FLORES-6',
        'PAISLEY-6',
        'ANIMAL PRINT-6',
        'RAYAS-6',
        'PUNTOS-6',
        'TROPICAL-6',
        'LISO-6',
        'OTRO-6',
        'ENCAJE-12',
        'TULL-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'CINTA-12',
        'NUDO-12',
        'TRANSPARENCIA-12',
        'CORDON/TIRA-12',
        'CINTURON-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'PARKAS': [
        'MEDIO-3',
        'TOBILLO-3',
        'LARGO-3',
        'PARKA-5',
        'FLORES-6',
        'PAISLEY-6',
        'LISO-6',
        'OTRO-6',
      ],      
      'PONCHOS': [
        'LANA-5',
        'HILO-5',
        'CHEVRON (ZIGZAG)-6',
        'LISO-6',
      ],
      'VESTIDO': [
        'MINI-15',
        'MIDI-15',
        'MAXI-15',
        'DESIGUAL-15',
        'STRAPLESS-2',
        'MANGA LARGA - CLASICA-2',
        'MANGA LARGA - FLARE-2',
        'MANGA CORTA -GLOBO-2',
        'MANGA CORTA - MURCIELAGO-2',
        'MANGA CORTA - FLARE-2',
        'MANGA CORTA - CLASICA-2',
        'SIN MANGA-2',
        'TIRITAS-2',
        'OFF SHOULDER-2',
        'COLD SHOULDER-2',
        'MANGA 3/4-2',
        'FORMA A-16',
        'BARDOT-16',
        'SKATER-16',
        'SLIP-16',
        'SMOCK-16',
        'WRAP-16',
        'PEPLUM-16',
        'FIT & FLARE (AJUSTADO Y ACAMPANADO)-16',
        'CINTURA CAIDA (AÑOS 20)-16',
        'CORTE IMPERIO (ABAJO PECHUGA)-16',
        'SHIFT-16',
        'STRAPLESS-1',
        'CUELLO V-1',
        'CUELLO REDONDO-1',
        'ESCOTE CRUZADO (WRAP)-1',
        'CINTA-1',
        'CUADRADO-1',
        'ESCOTE CORAZÓN-1',
        'CUELLO BOTE-1',
        'OTRO-1',
        'PLUMETI-5',
        'JACQUARD-5',
        'BLUE JEAN-5',
        'TENCEL-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'LINO-5',
        'GAMUZA-5',
        'ALGODON-5',
        'CREPE-5',
        'ENCAJE-5',
        'POPELINA-5',
        'CHIFFON-5',
        'PLISADO-5',
        'BRODERIE-5',
        'LANA-5',
        'HILO-5',
        'OTRA-5','CHEVRON (ZIGZAG)-6',
        'FLORES-6',
        'PAISLEY-6',
        'RAYAS-6',
        'PUNTOS-6',
        'TROPICAL-6',
        'LISO-6',
        'OTRO-6',
        'ENCAJE-12',
        'TULL-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'CINTA-12',
        'NUDO-12',
        'TRANSPARENCIA-12',
        'CORDON/TIRA-12',
        'CINTURON-12',
        'ACANALADO-12',
        'NIDO ABEJA-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'ENTERITOS': [
        'MINI-15',
        'MIDI-15',
        'MAXI-15',
        'STRAPLESS-2',
        'MANGA LARGA - CLASICA-2',
        'MANGA LARGA - FLARE-2',
        'MANGA CORTA -GLOBO-2',
        'MANGA CORTA - MURCIELAGO-2',
        'MANGA CORTA - FLARE-2',
        'MANGA CORTA - CLASICA-2',
        'SIN MANGA-2',
        'TIRITAS-2',
        'OFF SHOULDER-2',
        'COLD SHOULDER-2',
        'MANGA 3/4-2',
        'STRAPLESS-1',
        'CUELLO V-1',
        'CUELLO REDONDO-1',
        'ESCOTE CRUZADO (WRAP)-1',
        'CINTA-1',
        'CUADRADO-1',
        'ESCOTE CORAZÓN-1',
        'CUELLO BOTE-1',
        'OTRO-1',
        'BLUE JEAN-5',
        'TENCEL-5',
        'LINO-5',
        'ALGODON-5',
        'CHEVRON (ZIGZAG)-6',
        'FLORES-6',
        'PAISLEY-6',
        'RAYAS-6',
        'PUNTOS-6',
        'TROPICAL-6',
        'LISO-6',
        'OTRO-6',
        'ENCAJE-12',
        'TULL-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'CINTA-12',
        'NUDO-12',
        'TRANSPARENCIA-12',
        'CORDON/TIRA-12',
        'CINTURON-12',
        'ACANALADO-12',
        'NIDO ABEJA-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'SWEATERS (CERRADOS)': [
        'CROP-3',
        'NORMAL-3',
        'LARGA-3',
        'MANGA LARGA - CLASICA-2',
        'MANGA LARGA - FLARE-2',
        'MANGA CORTA -GLOBO-2',
        'MANGA CORTA - MURCIELAGO-2',
        'MANGA CORTA - FLARE-2',
        'MANGA CORTA - CLASICA-2',
        'OFF SHOULDER-2',
        'COLD SHOULDER-2',
        'MANGA 3/4-2',
        'NORMAL-4',
        'CUELLO V-1',
        'CUELLO REDONDO-1',
        'ESCOTE CRUZADO (WRAP)-1',
        'CINTA-1',
        'CUELLO BOTE-1',
        'OTRO-1',
        'TERCIOPELO-5',
        'PLUSH-5',
        'ALGODON-5',
        'LANA-5',
        'HILO-5',
        'OTRA-5',
        'CHEVRON (ZIGZAG)-6',
        'FLORES-6',
        'RAYAS-6',
        'PUNTOS-6',
        'TROPICAL-6',
        'LISO-6',
        'OTRO-6',
        'ENCAJE-12',
        'TULL-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'CINTA-12',
        'NUDO-12',
        'TRANSPARENCIA-12',
        'CORDON/TIRA-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'SWEATERS (ABIERTOS)': [
        'NORMAL-3',
        'LARGO-3',
        'MANGA LARGA - CLASICA-2',
        'MANGA CORTA - CLASICA-2',
        'MANGA 3/4-2',
        'NORMAL-4',
        'CUELLO V-1',
        'CUELLO REDONDO-1',
        'ESCOTE CRUZADO (WRAP)-1',
        'CINTA-1',
        'OTRO-1',
        'TERCIOPELO-5',
        'PLUSH-5',
        'ALGODON-5',
        'LANA-5',
        'HILO-5',
        'OTRA-5',
        'CHEVRON (ZIGZAG)-6',
        'FLORES-6',
        'PAISLEY-6',
        'RAYAS-6',
        'PUNTOS-6',
        'TROPICAL-6',
        'LISO-6',
        'OTRO-6',
        'ENCAJE-12',
        'TULL-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'CINTA-12',
        'NUDO-12',
        'TRANSPARENCIA-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'POLERONES (ABIERTOS O CERRADOS)': [
        'CROP-3',
        'NORMAL-3',
        'LARGA-3',
        'MANGA LARGA - CLASICA-2',
        'MANGA CORTA - CLASICA-2',
        'MANGA 3/4-2',
        'NORMAL-4',
        'CUELLO V-1',
        'CUELLO REDONDO-1',
        'CUELLO BOTE-1',
        'OTRO-1',
        'TERCIOPELO-5',
        'PLUSH-5',
        'ALGODON-5',
        'OTRA-5',
        'FLORES-6',
        'RAYAS-6',
        'PUNTOS-6',
        'TROPICAL-6',
        'LISO-6',
        'OTRO-6',
        'ENCAJE-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'TRANSPARENCIA-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'JEANS': [
        'ALTO (HIGH RISE)-8',
        'NORMAL (A LA CINTURA)-8',
        'CULOTTE (PANTORILLA)-7',
        'CROP (T[OBILLO)-7',
        'REGULAR-7',
        'FLARE-9',
        'RECTO-9',
        'PITILLO (SKINNY)-9',
        'WIDE-9',
        'CORTE BOTA-9',
        'OTRO-9',
        'BLUE JEAN-5',
        'FLORES-6',
        'PAISLEY-6',
        'RAYAS-6',
        'PUNTOS-6',
        'TROPICAL-6',
        'LISO-6',
        'OTRO-6',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'PANTALONES': [
        'ALTO (HIGH RISE)-8',
        'NORMAL (A LA CINTURA)-8',
        'CULOTTE (PANTORILLA)-7',
        'CROP (TOBILLO)-7',
        'REGULAR-7',
        'FLARE-9',
        'RECTO-9',
        'PITILLO (SKINNY)-9',
        'WIDE-9',
        'CORTE BOTA-9',
        'PLISADO-9',
        'OTRO-9',
        'JACQUARD-5',
        'TENCEL-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'LINO-5',
        'GAMUZA-5',
        'ALGODON-5',
        'GABARDINA-5',
        'COTELE-5',
        'PLISADO-5',
        'LANA-5',
        'HILO-5',
        'OTRA-5',
        'FLORES-6',
        'PAISLEY-6',
        'RAYAS-6',
        'PUNTOS-6',
        'TROPICAL-6',
        'LISO-6',
        'OTRO-6',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'PATAS': [   
        'NORMAL (A LA CINTURA)-8',
        'REGULAR-7',
        'RECTO-9',
        'TERCIOPELO-5',
        'PLUSH-5',
        'ALGODON-5',
        'OTRA-5',
        'FLORES-6',
        'PAISLEY-6',
        'RAYAS-6',
        'PUNTOS-6',
        'TROPICAL-6',
        'LISO-6',
        'OTRO-6',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'OTRO-12',
        'NINGUNO-12',
      ],   
      'SHORTS': [
        'ALTO (HIGH RISE)-8',
        'NORMAL (A LA CINTURA)-8',
        'CORTO-14',
        'NORMAL-14',
        'BERMUDA-14',
        'JACQUARD-5',
        'BLUE JEAN-5',
        'TENCEL-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'LINO-5',
        'GAMUZA-5',
        'ALGODON-5',
        'COTELE-5',
        'PLISADO-5',
        'LANA-5',
        'HILO-5',
        'OTRA-5',
        'CHEVRON (ZIGZAG)-6',
        'FLORES-6',
        'PAISLEY-6',
        'RAYAS-6',
        'PUNTOS-6',
        'TROPICAL-6',
        'LISO-6',
        'OTRO-6',
        'ENCAJE-12',
        'TULL-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'FALDAS': [
        'MINI-15',
        'MIDI-15',
        'MAXI-15',
        'DESIGUAL-15',
        'PLUMETI-5',
        'JACQUARD-5',
        'BLUE JEAN-5',
        'TENCEL-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'LINO-5',
        'GAMUZA-5',
        'ALGODON-5',
        'COTELE-5',
        'PLISADO-5',
        'LANA-5',
        'HILO-5',
        'OTRA-5',
        'CHEVRON (ZIGZAG)-6',
        'FLORES-6',
        'PAISLEY-6',
        'RAYAS-6',
        'PUNTOS-6',
        'TROPICAL-6',
        'LISO-6',
        'OTRO-6',
        'ENCAJE-12',
        'TULL-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'CINTA-12',
        'NUDO-12',
        'TRANSPARENCIA-12',
        'OTRO-12',
        'NINGUNO-12',
      ],
      'SKORTS': [
        'PLUMETI-5',
        'JACQUARD-5',
        'BLUE JEAN-5',
        'TENCEL-5',
        'TERCIOPELO-5',
        'PLUSH-5',
        'LINO-5',
        'GAMUZA-5',
        'ALGODON-5',
        'COTELE-5',
        'BRODERIE-5',
        'OTRA-5',
        'CHEVRON (ZIGZAG)-6',
        'FLORES-6',
        'PAISLEY-6',
        'RAYAS-6',
        'PUNTOS-6',
        'TROPICAL-6',
        'LISO-6',
        'OTRO-6',
        'ENCAJE-12',
        'TULL-12',
        'LENTEJUELAS-12',
        'BORDADO-12',
        'MOSTACILLAS-12',
        'TRANSPARENCIA-12',
        'OTRO-12',
        'NINGUNO-12',
      ]
    }
  end

end
